pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - status-success=Jenkins/front-end/build-status
      - status-success=Jenkins/back-end/build-status
      - label=automerge
    actions:
      delete_head_branch: {}
      review: {
        type: APPROVE,
        message: "LGTM"
      }
      merge:
        method: merge
        strict: true
