version: "3.3"

services:
  restapi:
    build: .
    restart: always
    container_name: rest-api
    ports:
      - 5000:8080
    working_dir: /opt/app
    environment:
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: rest-api-mongo
    volumes:
      - $HOME/data/rest-api-mongo-data:/data/db
      - $HOME/data/rest-api-mongo-bkp:/data/bkp
    restart: always
