pipeline {
  agent any

  environment {
    SECRET_KEY = credentials('jenkins-aws-secret-key-id')
    ACCESS_KEY = credentials('jenkins-aws-secret-access-key')
    JWT_SECRET = credentials('jenkins-jwt-secret')
    REFRESH_SECRET = credentials('jenkins-refresh-secret')
  }
  stages {
    stage('Build') {
      steps {
        echo 'Building...'
        sh './build.sh'
      }
    }
    stage('Lint') {
      steps {
        echo 'Linting...'
        sh './lint.sh'
      }
    }
    stage('Test') {
      steps {
        echo 'Testing...'
        sh './test.sh'
      }
    }
    stage('Coverage') {
      steps {
        echo 'Getting coverage...'
        sh './coverage.sh'
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
        expression {
          currentBuild.result == null || currentBuild.result == 'SUCCESS'
        }
      }
      steps {
        echo 'Deploying...'
      }
    }
  }
}